In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr.shape

(3, 3)

In [6]:
arr = arr*2

In [7]:
print(arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
